# Generated by Django 5.0.3 on 2024-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('icon', models.ImageField(upload_to='weather_icons/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
